version: '3.7'

services:
  api_gateway:
    image: nginx:alpine
    volumes:
      - ../:/var/www:delegated
      - ./nginx/:/etc/nginx/conf.d:delegated
      - ./nginx/vhosts:/etc/nginx/vhosts:delegated
      - ./nginx/logs:/var/log/nginx:delegated
    depends_on:
      - php-fpm-api-gateway
  php-fpm-api-gateway:
    #build:
      #context: php-fpm
      #dockerfile: Dockerfile
    image: fromsi/php-fpm
    volumes:
      - ../:/var/www:delegated
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:delegated
      - ~/.ssh:/home/www-data/.ssh:delegated
